const ENTITY_TYPES = {
    USER: 'USER',
    ROLE: 'ROLE',
    PERMISSION: 'PERMISSION',
    PERMISSION_GROUP: 'PERMISSION_GROUP',
    RESOURCE: 'RESOURCE',
    RESOURCE_ACTION: 'RESOURCE_ACTION',
    AUDIT_LOG: 'AUDIT_LOG',
};

const AUDIT_TYPES = {
    SYSTEM: 'SYSTEM',
    BUSINESS: 'BUSINESS'
};

const AUDIT_LOG_TYPES = {
    SYSTEM: {
        ERROR: 'ERROR'
    },
    AUTH: {
        LOGIN: 'LOGIN',
        LOGOUT: 'LOGOUT',
        LOGIN_FAILED: 'LOGIN_FAILED',
        LOGIN_SUCCESS: 'LOGIN_SUCCESS'
    },
    USER: {
        CREATE: 'USER_CREATE',
        UPDATE: 'USER_UPDATE',
        DELETE: 'USER_DELETE',
        DELETE_WITH_AUDIT: 'USER_DELETE_WITH_AUDIT',
        STATUS_CHANGE: 'USER_STATUS_CHANGE',
        PASSWORD_CHANGE: 'USER_PASSWORD_CHANGE',
        PASSWORD_CHANGE_FAILED: 'USER_PASSWORD_CHANGE_FAILED',
        ACTIVATE: 'USER_ACTIVATE',
        DEACTIVATE: 'USER_DEACTIVATE',
        PROFILE_UPDATE: 'USER_PROFILE_UPDATE',
        AVATAR_UPDATE: 'USER_AVATAR_UPDATE'
    },
    ROLE: {
        CREATE: 'ROLE_CREATE',
        UPDATE: 'ROLE_UPDATE',
        DELETE: 'ROLE_DELETE',
        DELETE_ATTEMPT: 'ROLE_DELETE_ATTEMPT'
    },
    PERMISSION: {
        CREATE: 'PERMISSION_CREATE',
        UPDATE: 'PERMISSION_UPDATE',
        DELETE: 'PERMISSION_DELETE',
        GROUP_CREATE: 'PERMISSION_GROUP_CREATE',
        GROUP_UPDATE: 'PERMISSION_GROUP_UPDATE'
    },
    RESOURCE: {
        CREATE: 'RESOURCE_CREATE',
        UPDATE: 'RESOURCE_UPDATE',
        DELETE: 'RESOURCE_DELETE',
        ACTIONS_UPDATE: 'RESOURCE_ACTIONS_UPDATE'
    },
    AUDIT: {
        EXPORT: 'AUDIT_EXPORT',
        EXPORT_SUCCESS: 'AUDIT_EXPORT_SUCCESS',
        EXPORT_ERROR: 'AUDIT_EXPORT_ERROR'
    }
};

module.exports = {
    ENTITY_TYPES,
    AUDIT_TYPES,
    AUDIT_LOG_TYPES
};